---
- name: mesos-master
  hosts: '{{ target }}'
  gather_facts: yes
  become: true
  become_user: root
  tasks:
    - name: package updates
      yum:
        name: '*'
        state: latest

    - name: check mesos downloaded file
      stat:
        path: /opt/mesos-{{ mesos_version }}.tar.gz
      register: mesos_downloaded

    - name: download mesos when not downloaded
      get_url:
        url: http://www.apache.org/dist/mesos/{{ mesos_version }}/mesos-{{ mesos_version }}.tar.gz
        dest: /opt/
        mode: '0440'
      when: mesos_downloaded.stat.exists == false

    - name: check mesos unarchived file (README file)
      stat:
        path: /opt/mesos-{{ mesos_version }}/README.md
      register: mesos_unarchived

    - name: unarchive mesos when not unarchived
      unarchive:
        src: /opt/mesos-{{ mesos_version }}.tar.gz
        dest: /opt
        remote_src: yes
      when: mesos_unarchived.stat.exists == false

    - name: mesos version to /opt/mesos softlink
      file:
        src: /opt/mesos-{{_version }}
        path: /opt/mesos
        state: link
        mode: '0755'
        owner: root
        group: root

    - name: mesos unit file
      template:
        src: mesos-master.service
        dest: /etc/systemd/system/mesos-master.service
        owner: root
        group: wheel
        mode: u=rw,g=r,o=r

    - name: mesos systemd service
      systemd:
        state: started
        enabled: yes
        daemon_reload: yes
        name: mesos-master
